# Generated by Django 4.2.1 on 2023-06-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationPlanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_plans', models.ManyToManyField(to='company.vacationplan')),
            ],
        ),
        migrations.CreateModel(
            name='GetUpdateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_updates', models.ManyToManyField(to='company.getupdate')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusiveDealGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusive_deals', models.ManyToManyField(to='company.exclusivedeal')),
            ],
        ),
    ]
